config/routes.rb
Rails.application.routes.draw do
  get 'post/index'

  root 'post#index'

  
  get 'newpost' => 'post#new'
  post "processpost" => "post#addpost"

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/postdatecount.rb
class Postdatecount < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    
    # If no date is in the querystring then we use the current date
    if params[:datefilter] == nil
      # Show the post from the current month and year order by descending
      @posts = Post.where ( ["month = ? and year = ?" , Date.today.month , Date.today.year])
      
    else
      # parse the date in the params
      yearFilter = params[:datefilter][0..3].to_i
      monthFilter = params[:datefilter][4..5].to_i
      
      @posts = Post.where ( ["month = ? AND year = ?" , monthFilter , yearFilter])
      
    end
    
    
  end
  
  
  def new
    
  end
  
  
  def addpost
    bodytext = params[:postbody]
    username = params[:name]
    
    if username == nil || username = ""
      username = "Anonymous"  
    end
    
    
    newPost = Post.new
    newPost.body = bodytext
    newPost.name = username
    newPost.month = Date.today.month
    newPost.year = Date.today.year
    newPost.save!
    
    
    # Update the number of post for the month
    # Check if the month and year exist first
    
    dcount = Postdatecount.where( ["month = ? AND year = ?" , Date.today.month , Date.today.year])
    
    if dcount.size > 0
      # If exist, then we add to the count
      dateCount = Postdatecount.where ( ["month = ? AND year = ?" , Date.today.month , Date.today.year ])
      dateCount = dateCount.first
      dateCount.postcount = dateCount.postcount + 1 
      dateCount.save!
      
    else  
    # If does not exist, then we insert the month and add count as 1
      newDateCount = Postdatecount.new
      newDateCount.month = Date.today.month
      newDateCount.year = Date.today.year
      newDateCount.postcount = 1
      newDateCount.save!
    end

    redirect_to root_path
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ptnet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href="http://bootswatch.com/simplex/bootstrap.min.css" type='text/stylesheet' rel='stylesheet' />
  
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  
  <div class="row">
  
    <div class="col-md-12">
      <h1>P.net</h1>
      <h4>The only place on the Internet <!--where you can let things off your chest without people judging you. No registering too, ever. --> </h4>
    </div>
    
  </div>
  

<%= yield %>
</div> <!-- Close container -->
</body>
</html>

app/views/post/_postbody.html.erb
<div class="col-md-12 rounded-border img-rounded" style="padding:10px;">
  <p class="bodytext"><%= postbody.body %>
  </p>

  <p>
  <div class="text-right">
    Posted by <%= postbody.name %> <%= time_ago_in_words(postbody.created_at) %> ago  
  </div>
  </p>
</div>

app/views/post/index.html.erb
<div class="row">

  <div class="col-md-10">
    <%= render :partial => "postbody" , :collection => @posts.order(:created_at).reverse_order %>
  </div>

  <div class="col-md-2">
    <div class="col-md-12">
      <%= link_to "Post New Message", newpost_path , :class => "btn btn-success" %>

    </div>

    <br />
    <br /><br />
    <div class="col-md-12">
      <% 
startDate = Date.new(2014 , 2 , 1)  
      currentDate = Date.today
        
while currentDate  >= startDate do
  %>
  
      <%= link_to currentDate.strftime("%B %Y") , root_path(:datefilter => currentDate.strftime("%Y%m")) %>
      <br />      
      <%
    currentDate = currentDate - 1.month
end
%>
    </div>
  </div>
</div> 

app/views/post/new.html.erb
<div class="row">

  <div class="col-md-12">
    <h3>I feel you, just let your feelings out .... </h3>
  </div>
  
  <div class="col-md-9">
    <%= form_tag processpost_path , method: "post" , role: "form" do %>
      
      <textarea name="postbody" class="form-control" rows="6" placeholder="What do you want to say .."></textarea>
      <br />
      <input type="text" name="name" class="form-control" placeholder="Your Name (Optional)" />
      <Br />
    <button type="submit" class="btn btn-success" value="Submit">I'm done</button>
    <%= link_to "Cancel" , root_path , :class => "btn" %>

      
    <% end %>
  </div>
  
</div>